name: test

on:
  schedule:
    - cron: 30 8 * * 1
  workflow_dispatch:
    inputs:
    
jobs:
  test1:
    runs-on: ubuntu-latest
    name: test123
    continue-on-error: true
    timeout-minutes: 100

    steps:
      - uses: actions/checkout@v2
      - name: gclone Install
        run: |
         sudo apt update
         sudo mkdir newfolder
         sudo ls
         sudo apt install apt-transport-https
         wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -
         echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
         sudo apt update
         sudo apt install jellyfin
         sudo apt install nodejs
         sudo chmod 755 -R /newfolder
         sudo chown jellyfin:jellyfin /newfolder
         npx localtunnel --port 8096
        
