name: test

on:
  schedule:
    - cron: 30 8 * * 1
  workflow_dispatch:
    inputs:
    
jobs:
  test1:
    runs-on: ubuntu-latest
    name: test123
    continue-on-error: true
    timeout-minutes: 100

    steps:
      - uses: actions/checkout@v2
      - name: gclone Install
        run: |
          sudo wget https://github.com/MediaBrowser/Emby.Releases/releases/download/4.5.4.0/emby-server-deb_4.5.4.0_amd64.deb
          sudo dpkg -i emby-server-deb_4.5.4.0_amd64.deb
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.GCLONE_CONFIG_SYNC }}
          EOF
          rclone config file
          sudo rclone config file
          cd /
          cd ../../../..
          cd home
          sudo apt install nodejs
          sudo rclone mount MediaServer: /home --allow-other --daemon --allow-non-empty --cache-db-purge --buffer-size 32M --use-mmap --dir-cache-time 4h --drive-chunk-size 16M --timeout 1h --vfs-cache-mode minimal --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 1G --fast-list
          npx localtunnel --port 8096
        
