name: StartServer

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: JellyfinServer
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Jellyfin Install
        run: |
          mkdir config
          cd config
          wget https://github.com/cryptbphcoutlook/test123/raw/main/cloudflare/config.tar
          tar -xvf config.tar
          cd ..
          cd cloudflare
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          sudo apt install apt-transport-https
          wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -
          echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
          sudo apt update
          sudo apt install jellyfin
          sudo systemctl stop jellyfin
          sudo rm -r /var/lib/jellyfin
          cd ..
          cd config/var/lib/
          sudo cp -r jellyfin/ /var/lib/
          sudo chown -R jellyfin:jellyfin /var/lib/jellyfin
          sudo systemctl start jellyfin
          timeout 5m cloudflared tunnel --url localhost:8096
          sudo systemctl stop jellyfin
          cd cloudflare
          sudo tar -cvf config.tar /var/lib/jellyfin
          git config --global user.name 'cryptbphcoutlook'
          git config --global user.email 'cryptbphcoutlook@users.noreply.github.com'
          git add .
          git commit -am "Config File"
          git push
        
