name: test

on:
  schedule:
    - cron: 30 8 * * 1
  workflow_dispatch:
    inputs:
    
jobs:
  test1:
    runs-on: ubuntu-latest
    name: test123
    continue-on-error: true
    timeout-minutes: 100

    steps:
      - uses: actions/checkout@v2
      - name: gclone Install
        run: |
          sudo wget https://raw.githubusercontent.com/crypt-bphc/RDP-Colab/main/rdp.sh
          sudo chmod +x rdp.sh
          sudo ./rdp.sh
          sudo apt install nodejs
          npx localtunnel --port 5555
        
