name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'cryptbphcoutlook'
          git config --global user.email 'cryptbphcoutlook@users.noreply.github.com'
          git add .
          git commit -am "Automated report"
          git push
